name:         Config-General
version:      2.50
version_from: General.pm
installdirs:  site
requires:
    File::Glob:                    0
    File::Spec::Functions:         0
    FileHandle:                    0
    IO::File:                      0
resources:
    bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Config-General
    homepage:   http://search.cpan.org/dist/Config-General/
    license:    http://dev.perl.org/licenses/artistic.html
    repository: http://dev.catalyst.perl.org/repos/Config-General
distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
